# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: mariodr/legion-docker:ubuntu16.04

pipelines:
   default:
#    - step:
#        name: Compile prometeo
#        script: # Modify the commands below to build your repository.
#          - cd src
##          - make
#
      - parallel:
         - step:
            name: Test Config
            script:
               - cd unitTests/configTest
               - make
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - ./configTest.exec

         - step:
            name: Test math_utils
            script:
               - cd unitTests/mathUtilsTest
               - make
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - ./mathUtilsTest.exec

         - step:
            name: Test hdf_helper
            script:
               - cd unitTests/hdfTest
               - make
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - ./hdfTest.exec

         - step:
            name: Test mixtures
            script:
               - cd unitTests/mixTest
               - make
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - ./mixTest.exec

         - step:
            name: Test geometry
            script:
               - cd unitTests/geometryTest
               - make
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - ./geometryTest.exec

# We do not have enough memory for all the tests
         - step:
            name: Test metric
            script:
               - cd unitTests/metricTest
               - make metricTest_Periodic.exec
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - ./metricTest_Periodic.exec

         - step:
            name: Test cfl
            script:
               - cd unitTests/cflTest
               - make
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - ./cflTest.exec

         - step:
            name: Test chemistry
            script:
               - cd unitTests/chemTest
               - make
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - ./chemTest.exec

         - step:
            name: Test variables
            script:
               - cd unitTests/variablesTest
               - make
               - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LEGION_DIR/bindings/regent"
               - ./variablesTest.exec

